# Generated by Django 4.0.3 on 2022-09-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeClientes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(blank=True, db_column='Nombre_Apellido', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('ultimo_lavado', models.DateField(blank=True, db_column='Ultimo_lavado', null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('detalle', models.CharField(blank=True, db_column='Detalle', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
            ],
            options={
                'db_table': 'lista_de_clientes_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='agregar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
