# Generated by Django 4.0.3 on 2022-09-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agregar',
            options={'managed': False},
        ),
    ]
